deployment:
  replicas: 2
  image: gcr.io/famous-archway-358310/demo-crm:latest
  imagePullPolicy: Always
  resources: {}
  # deployment:
  #   resources:
  #     requests:
  #       cpu: "0.4"
  #       memory: 400Mi
  #     limits:
  #       cpu: "0.8"
  #       memory: 800Mi

# -------
configMap:
  data: {}
  # configMap:
  #   data:
  #     LOG_LEVEL: info
  #     PERSISTENCE: "true"

# -------
secret:
  data: {}
  # secret:
  #   data:
  #     MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6c2VjcmV0LXJvb3QtcHdkQG1vbmdvZGItMC5tb25nb2RiLWhlYWRsZXNzOjI3MDE3Lz9hdXRoU291cmNlPWFkbWluJnJlcGxpY2FTZXQ9cnMwCg==

# -------
service:
  port: 80
  type: ClusterIP

# -------
ingress:
  enabled: true
  annotations: {}

  host: oshricowsay.no-ip.org
  path: "/"
  tls:
    enabled: false
    hosts: oshricowsay.no-ip.org
    secretName: nginx-tls

  # ingress:
  #   enabled: true
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #     cert-manager.io/cluster-issuer: letsencrypt-prod
  #   tls:
  #     enabled: true
# -------

CronJob:
  enable: false
  schedule: "* * * * *"
