{{- if .Values.ingress.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron-purge
spec:
  schedule: {{ .Values.CronJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: runner
              image: mongo
              env:
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: crm-secret
                    key: MONGODB_URI
              command: ["mongosh", $(MONGODB_URI), "--eval", "db.dropDatabase()"]
              securityContext:
                runAsUser: 0
{{- end }}

