{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-app-crm
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ .Release.Name }}-nextjs
            port: 
              number: 80
  {{- if .Values.ingress.tls.enabled }}            
  tls:
  - hosts: 
    - {{ .Values.ingress.tls.hosts }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}