apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'git@github.com:oshriza/demo-crm-chart.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - stg-values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true