apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"

  project: default
  syncPolicy:
    automated:
      selfHeal: true