apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.helm.sh/stable'
    targetRevision: 1.3.0
    chart: nginx-ingress
  project: default
  syncPolicy:
    automated:
      selfHeal: true