apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: mongo
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 13.0.0
    chart: mongodb
    helm:
      values: |
        architecture: replicaset
        replicaCount: 3
        persistence:
          storageClass: "standard"
        auth:
          rootPassword: secret-root-pwd
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true